export const CREATE_TRANASACTION = 'CREATE_TRANASACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';