export const CREATE_TRANASACTION = 'CREATE_TRANASACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SET_CARDS = 'SET_CARDS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
