//--- transactions types
export const CREATE_TRANASACTION = 'CREATE_TRANASACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const TRANSACTIONS_LOADED = 'TRANSACTIONS_LOADED';
export const MORE_TRANSACTION_LOADING = 'MORE_TRANSACTION_LOADING';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';


//--- user types
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SET_USER = 'SET_USER';

//--- card types
export const SET_NEXT_CARD = 'SET_NEXT_CARD';
export const SET_PERV_CARD = 'SET_PERV_CARD';
export const SET_CARDS = 'SET_CARDS';
export const CREATE_CARD = 'CREATE_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';

//--- app types
export const INITIALIZE_SUCCESS = 'INITIALIZE_SUCCESS';
export const START_LOGIN = 'START_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';